### ISSUE TITLE
issue with logging into apache after baruwa isntall.sh

### ISSUE THREAD

**Issue by jmhorne125** [fluxlabs/baruwa#58]
Hello, after completing the installer script (fantastic work BTW), i am unable to log into the web interface.  i get this error (and an email in my inbox) each time i try to access a URL:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.27 (CentOS) Server at 10.125.59.64 Port 80

i also see these in the baruwa apache logs:

==> /var/log/httpd/baruwa-error_log <==
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208] Error - <type 'exceptions.DeprecationWarning'>: You passed charset='iso-8859-1' to the Request constructor. As of WebOb 1.2, if your application needs a non-UTF-8 request charset, please construct the request without a charset or with a charset of 'None',  then use ``req = req.decode(charset)``
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208] mod_wsgi (pid=18049): Exception occurred processing WSGI script '/home/baruwa/px/lib/python2.6/site-packages/baruwa/baruwa.wsgi'.
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208] Traceback (most recent call last):
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/home/baruwa/px/lib/python2.6/site-packages/paste/registry.py", line 379, in __call__
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     app_iter = self.application(environ, start_response)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/home/baruwa/px/lib/python2.6/site-packages/pylons/middleware.py", line 177, in __call__
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     self.app, new_environ, catch_exc_info=True)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/home/baruwa/px/lib/python2.6/site-packages/pylons/util.py", line 50, in call_wsgi_application
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     app_iter = application(environ, start_response)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/home/baruwa/px/lib/python2.6/site-packages/weberror/errormiddleware.py", line 156, in __call__
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     return self.application(environ, start_response)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/usr/lib/python2.6/site-packages/repoze.who-1.0.19-py2.6.egg/repoze/who/middleware.py", line 65, in __call__
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     ids = self.identify(environ, classification)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/usr/lib/python2.6/site-packages/repoze.who-1.0.19-py2.6.egg/repoze/who/middleware.py", line 162, in identify
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     identity = plugin.identify(environ)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/usr/lib/python2.6/site-packages/repoze.who_friendlyform-1.0.8-py2.6.egg/repoze/who/plugins/friendlyform.py", line 122, in identify
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     request = Request(environ, charset=self.charset)
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]   File "/home/baruwa/px/lib/python2.6/site-packages/webob/request.py", line 138, in __init__
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208]     "req.decode(charset)``" % charset
[Mon Apr 06 12:22:21 2015] [error] [client 10.125.57.208] DeprecationWarning: You passed charset='iso-8859-1' to the Request constructor. As of WebOb 1.2, if your application needs a non-UTF-8 request charset, please construct the request without a charset or with a charset of 'None',  then use ``req = req.decode(charset)``

==> /var/log/httpd/baruwa-access_log <==
10.125.57.208 - - [06/Apr/2015:12:22:18 -0500] "GET /settings/node/add HTTP/1.1" 500 612

any recommendations, or can i provide something else to help troubleshooting?

**Comment by fluxlabs** [comment]
Looks like your locale is non UTF-8. Fix that then regen, and try again.

You passed charset='iso-8859-1' to the Request constructor. As of WebOb 1.2, if your application needs a non-UTF-8 request charset

--
Jeremy McSpadden
Flux Labs | http://www.fluxlabs.net<http://www.fluxlabs.net/> | Endless Solutions
Office : 850-250-5590x501<tel:850-250-5590;501> | Cell : 850-890-2543<tel:850-890-2543> | Fax : 850-254-2955<tel:850-254-2955>

**Comment by jmhorne125** [comment]
The server appears to be set right:

[root@dlp-upcent64 conf.d]# env|grep LANG
LANG=en_US.UTF-8

[root@dlp-upcent64 conf.d]# cat /etc/httpd/conf/httpd.conf | grep -i utf-8
IndexOptions FancyIndexing VersionSort NameWidth=* HTMLTable Charset=UTF-8
AddDefaultCharset UTF-8

Is there another place I need to look?

Also, im not familiar with what you mean by “regen”, can you be more specific (or point me to what I need to read…im unfortunately not a programmer).
